#Deployment
apiVersion: v1
kind: Deployment
metadata:
  name: bot
  namespace: tg-bot
  labels:
    app: bot
  spec:
    replicas: 1
    strategy:
    type: RollingUpdate
    RollingUpdate:
      maxUnvailable: 1
      maxSurve: 0
    selector:
      matchLabels:
        app: bot
    template:
      metadata:
        labels:
          app: bot
      spec:
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        nodeSelector:
          location: amsterdam
      containers:
      - name: bot
      image: ./Dokerfile
      ports:
      - containerPort: 8080
      - protocol: TCP
    resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
    readinessProbe:
      httpGet:
        path: /
        port: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    





---
# Servise
apiVersion: v1
kind: Servise
metadata: 
  name: bot
  namespace: tg-bot
  labels:
    app: bot
  spec:
    type: ClusterIP
    selector:
      app: bot
    port : 8080
    name: health-check
    targetPort: 8080
    protocol: TCP


